### ISSUE TITLE
Is there any way to modify incoming server data?

### ISSUE THREAD

**Issue by juanogcx** [stefffdev/NubeSync#20]
Hi @stefffdev, not an issue but more a question. I have an use case that I haven't been able to satisfy. I have an "Order" table, but I will need to generate a custom sequential number per customer(from one or more devices for the same customer), so, this data can't be calculated/sent securely from client. 

So, the order gets "persisted" from the device, from the sync operation, so I can't just intercept the save operation as it's done on server via `OperationsController`, not on my "`OrdersController`". 

So in general, is there any advice on how to intercept the save operation and modify the it's data on a table on server? On a follow up: if there's a way: how could the client know the data changed: is a full sync maybe expected?

**Comment by stefffdev** [comment]
Hi,

we will have a similar requirement in the near future!

I was thinking that *ProcessOperationsAsync* could return a list of all the records that were touched, you could filter them then by type and post-process them.

The client will get that changes with the next pull (which should be done after each pull anyways).

What do you think?

**Comment by juanogcx** [comment]
Yeah that option sounds good! Do you think that feature will come soon? Any ETA that you could imagine?

Thanks for replying!

**Comment by stefffdev** [comment]
I will have a look at it soon, shouldn't be too much work! 👍

**Comment by stefffdev** [comment]
I just published a pre release (1.5.0-pre) to nuget, that should allow post processing of the records.
See this wiki page for documentation https://github.com/stefffdev/NubeSync/wiki/Post-Process-pushed-records

Let me know if this works for you.

**Comment by juanogcx** [comment]
Many thanks @stefffdev I will give it a try today.
