### ISSUE TITLE
Cannot push operations to the server: BadRequest

### ISSUE THREAD

**Issue by bitoul** [stefffdev/NubeSync#25]
{NubeSync.Client.PushOperationFailedException: Cannot push operations to the server: BadRequest An error occurred while updating the entries. See the inner exception for details.  at NubeSync.Client.NubeClient.PushChangesAsync (System.Threading.CancellationToken cancelToken) [0x0038c] in <3e398073457747968f6379ca8bad6a1c>:0   at Ebas_Attend.ViewModels.PunchedVM.PunchedFun () [0x0076e] in C:\Users\User\source\repos\Ebas_Attend\Ebas_Attend\Ebas_Attend\ViewModels\PunchedVM.cs:559 }

hi, I am new to this thing so I will try to explain what happens. 
I make a web API (.net 5.0) in azure I follow this wiki (https://github.com/stefffdev/NubeSync/wiki/Creating-a-ASP.NET-Core-Backend)
and in my client xamarin forms, i follow this (https://github.com/stefffdev/NubeSync/wiki/Creating-a-Xamarin-Forms-client-app)
and everything is working for a while but after some PushChangesAsync and PullTableAsync, this BadRequest happens When I try to make a PushChangesAsync. 
Now, all the clients are stuck in a state where it can't make a PushChangesAsync.

I clean all data from the database and from the client and the problem is still there, the only way is to drop down the web API 
from azure and publish it again.

**Comment by stefffdev** [comment]
Hi,
on the first sight this looks like https://github.com/stefffdev/NubeSync/issues/23 

Which should be fixed in the latest version (1.5.0) - so could you update to 1.5.0 and report back if this problem is still there?
thx

**Comment by bitoul** [comment]
hi, thanks for your fast response. yes, I read #23.
I am on the latest version (1.5.0) from the beginning and if is the same problem is still there.

**Comment by stefffdev** [comment]
Ok, could you post the details of the exception that is thrown in the "PostOperationsAsync" method of the OperationsController on your server?

This exception should contain the details of what's going wrong here!

**Comment by bitoul** [comment]
InnerException	{"Violation of PRIMARY KEY constraint 'PK_Users'. Cannot insert duplicate key in object 'dbo.Users'. The duplicate key value is (user_1)."}	System.Exception {Microsoft.Data.SqlClient.SqlException}
is this the problem ? or i should try and send all the details of the exception

**Comment by bitoul** [comment]
but if this Violation is coming from the Database why when I delete all data from both Database and the Client is still there?

**Comment by stefffdev** [comment]
This is the error causing the problem, it looks like you have a foreign key somewhere on your User.
That's why it works for some time and the error occurs when a record is inserted where the key already exists.

Do you have a repo where I could look at your models?
Otherwise I think we can close this issue since it is not really related to NubeSync.

**Comment by bitoul** [comment]
this was the issue I don't know why and how but it's working thank sorry for your time !! thank again for the fast response.

**Comment by stefffdev** [comment]
👍
