### ISSUE TITLE
OperationService _GetTableType uses wrong class when names are conflicting

### ISSUE THREAD

**Issue by Toccata6767** [stefffdev/NubeSync#26]
I ran into this issue where if one of your NubeServerTables uses a name that is already in use by another assembly in the current app domain, then the server uses the wrong one when trying to process operations. For my specific example I used the name "Module" for one of my tables, while there was already a type with the name "Module" in the System.Reflection assembly. 

When ProcessOperationsAsync is iterating through the operations it uses a method called _GetTableType to get the matching type for the table name provided. It does this by first getting all of the assemblies in the current app domain and then getting all of the types in each of those assemblies. From that list it takes the first one where the type name matches the table name. This is not a safe assumption as this can return the wrong type in some cases like my example.

From line 142 in OperationService.cs in the NubeSync.Server project
```c#
var type = AppDomain.CurrentDomain
    .GetAssemblies()
    .SelectMany(x => x.GetTypes())
    .FirstOrDefault(t => t.Name == tableName);
```

If you can assume that these types should always inherit NubeServerTable, which I believe is a safe assumption, then this change will resolve the issue:

```c#
var type = AppDomain.CurrentDomain
    .GetAssemblies()
    .SelectMany(x => x.GetTypes())
    .SingleOrDefault(t => t.Name == tableName && t.BaseType == typeof(NubeServerTable));
```

**Comment by stefffdev** [comment]
Nice find, thx!
Until it is fixed you should be able to use this as a workaround:
https://github.com/stefffdev/NubeSync/wiki/Register-your-tables-server-side-for-faster-response-times

**Comment by Toccata6767** [comment]
Awesome thanks!
