### ISSUE TITLE
Unable to run Migrations

### ISSUE THREAD

**Issue by Jcardif** [stefffdev/NubeSync#3]
I Have followed all the steps described in the wiki but upon running the Migrations command on visual studio 2019 Get the error below 

![image](https://user-images.githubusercontent.com/29174946/94719418-cbbcfe00-035b-11eb-91d5-1a9ea5f9837a.png)

**Comment by stefffdev** [comment]
Hi Jcardif, this looks like a EF Core/ASP.NET problem, something similar to this: https://github.com/dotnet/EntityFramework.Docs/issues/1238

Did you use ASP.NET Core version 3.1? Cause that is the version we are using and the version the docs are tested against.

**Comment by Jcardif** [comment]
I am using version 3.1.402

**Comment by stefffdev** [comment]
You could give this one a try, providing a design time DbContext:
https://stackoverflow.com/a/60602620/6444248

**Comment by Jcardif** [comment]
I was able to build and create the migrations successfully however the warning is still there

![image](https://user-images.githubusercontent.com/29174946/94749557-c0ce9180-038c-11eb-8833-89f608ffbb36.png)

when running the app it crashes with the same error as before 

![image](https://user-images.githubusercontent.com/29174946/94750490-d6dd5180-038e-11eb-8228-43255722accf.png)

I cloned the repo and tried running the server project as well and the result is still the same

**Comment by stefffdev** [comment]
Sorry, there was a bug in the server sample, please have a look at the changeset that fixes this:
https://github.com/stefffdev/NubeSync/commit/91fe897b26b6965d30bff3f1d6d011b249199620

I'll have to update the docs as well, but in short you have to provide the types that should be synced to the operation service.
Hope that resolves this issue for you.

**Comment by Jcardif** [comment]
This finally works.
