### ISSUE TITLE
Geting all data from the table!!

### ISSUE THREAD

**Issue by bitoul** [stefffdev/NubeSync#32]
hi I think am missing something or am doing something wrong when I use ( _nubeClient.PullTableAsync<T>) to pull the data am getting all the data of the table, not just the USERS from where is the filtering is happening. 
Sorry for the question am new to this!! 

Thanks

**Comment by stefffdev** [comment]
Hi, do you mean you only want the records of the user that is pulling?

If so, then you need to somehow get the pulling user id in the controller (for example extract it from the authentication) and then filter the items by the user id.

Maybe you can get an idea how to do it by looking at this:
https://github.com/stefffdev/NubeSync/blob/df1c0180cbf2239e31bae77255d2eb1b88269442/samples/Backend/NubeSync.Service/Controllers/TodoItemsController.cs#L58

**Comment by bitoul** [comment]
Thank you for your fast reply!! Yes, this is exactly what I mean. 
Is there any other way to get the user id in the controller without the (authentication)?
It will be good if the (PullTableAsync()) can take a parameter like this?

**Comment by stefffdev** [comment]
You could create the HttpClient by yourself and add the user id as header, then receive it at the server side similar like this:
https://github.com/stefffdev/NubeSync/blob/df1c0180cbf2239e31bae77255d2eb1b88269442/samples/Backend/NubeSync.Service/Helpers/HttpRequestExtension.cs#L8

When creating the NubeSync client you can pass your own HttpClient in the constructor.

But be aware that this way it is very easy to get the data of another user, if I know the other users id and pass it in the header.
Therefore it is more secure to receive the user.id from the authentication.

**Comment by bitoul** [comment]
ok, thank you very much for your guidance!! you were very helpful.

**Comment by stefffdev** [comment]
👍
