### ISSUE TITLE
The type initializer for 'System.Text.Json.JsonSerializer' threw an exception

### ISSUE THREAD

**Issue by drowe5** [stefffdev/NubeSync#34]
Trying to get the Xamarin Forms iOS application running but get a serialization error when I press the Sync button in the sample provided here on GitHub.

I am compiling this on the most recent version of Visual Studio 2019 on Mac (8.10.14 (build 17)).  It's possible this may be caused by an issue with System.Text.Json but I have spent 2 days trying ways to work around that...to no avail.   (I've even tried converting Nube* from System.Text.Json to Newtonsoft--but ultimately that rabbit hole lead to other issues.)

Even though I'm using the sample I'm still going to add the solution that I'm reproducing this with.  My "offline.db" file has a single ToDo item in it (got there by me clicking the "Add Item" button in the sample)

Please help me get this running on iOS.  I'm really excited about using this but I can't get it working it.

<img width="905" alt="Exception" src="https://user-images.githubusercontent.com/14004618/144156849-9fd370ef-e771-47c5-813e-50a7a098a330.png">

<img width="372" alt="iPhone Simulator" src="https://user-images.githubusercontent.com/14004618/144156883-52112845-6c78-40f6-8a06-5c8468a72d82.png">
<img width="1033" alt="NubeOperation table" src="https://user-images.githubusercontent.com/14004618/144155974-af112cb0-1907-40d3-96e8-9e6cd93bc7dc.png">
<img width="605" alt="ToDoItem table" src="https://user-images.githubusercontent.com/14004618/144155983-ddb18f4d-954f-44e8-8856-89551a424f84.png"> 

[samples.zip](https://github.com/stefffdev/NubeSync/files/7629977/samples.zip)

[StackTrace.txt](https://github.com/stefffdev/NubeSync/files/7629967/StackTrace.txt)

[offline.db.zip](https://github.com/stefffdev/NubeSync/files/7630004/offline.db.zip)

**Comment by stefffdev** [comment]
Hi, thx for the detailed report.

The problem seems to be the "MissingMethodException" within the TypeInitializationException.
Following the accepted answer from https://docs.microsoft.com/en-us/answers/questions/302548/jsonserializer-throws-exception-in-xamarinios.html did fix it for me.

* Right click the **NubeSync.Mobile.iOS** project and select **Edit Project File**
* Add this at the end before the ```</Project>``` Tag and you should be fine:
```
  <ItemGroup> 
    <PackageReference Include="System.Memory" Version="4.5.4"> 
    <IncludeAssets>none</IncludeAssets> 
    </PackageReference> 
    <PackageReference Include="System.Buffers" Version="4.5.1"> 
    <IncludeAssets>none</IncludeAssets> 
    </PackageReference> 
  </ItemGroup> 
```

I will have to add that to the samples though.

**Comment by drowe5** [comment]
Thank you!  I (thought I) had tried that but apparently I didn’t do something correctly.  Tried again as you described and it seems to be working now.  Thanks again…fingers crossed everything goes well from here.

I truly appreciate the timely response!

Cheers!
