### ISSUE TITLE
Flutter version ?

### ISSUE THREAD

**Issue by stevehayles** [stefffdev/NubeSync#35]
Really great looking project, has there been any progress on a Flutter version ?

**Comment by stefffdev** [comment]
Hey, I'm using the Flutter version on an internal product, but I've never created a separate package for Flutter (mostly because I don't have any experience doing that).
Also the code would need some polish to be fully production ready.

Most of the users from this package come from the C# world and most Flutter apps I know use backends like Firestore and don't have a real demand for an offline sync framework, so I'm not sure if it's worth the effort...

**Comment by stevehayles** [comment]
Hi @stefffdev, thanks for the response, I apologise for using the issue tracker for this, not quite the right place maybe.  I am trying actively to avoid using Firestore as much as possible and most things are workable but a good sync framework is the missing bit for me.  Is the Flutter code you have something that you would consider releasing as part of this project or if not, under some other licensing agreement ?

**Comment by stefffdev** [comment]
Right now I don't plan on releasing the Flutter stuff in any ways, since I don't really have the time for it currently.
What we could do is that I hack some sample together when I've got some spare time and you try to make your way from there?

**Comment by stevehayles** [comment]
Totally understand and thanks again for your reply.  It would be absolutely fantastic to see even a quick 'hacked up' sample to see how you would approach this. I'm a C# developer from long before I looked at Dart and I would be hugely appreciative of any guidance

**Comment by stefffdev** [comment]
Out of curiosity, why didn‘t you pick Xamarin/Maui or uno?

**Comment by stevehayles** [comment]
I have built apps in Xamarin and Xamarin.Forms from quite early in their existence and it wasn't a great experience.  Uno always looked good but I never tried it beyond reading the docs.  Flutter made me instantly more productive and I really liked the general development cycle and the fact that my app simply looked so much better from the outset.  I found with Xamarin that I was building the logic layer forever and the app always looked terrible and with flutter the general aesthetic kept pace with the development.

The hot reloading was amazing and it's not just UI elements that could be updated and I don't think non Flutter users will realise just how powerful this is.  Business logic, services and and UI can all reloaded and it makes the development and debugging cycle really quick.

I think there other advantages around things like animations and not being tied to specific tooling but to be fair I haven't gone back to Maui recently and I do suspect my timing was such that I saw the worst of Xamarin and the best of Flutter and it might be a different story now!

**Comment by stefffdev** [comment]
That's exactly my experience as well - I also started with early Xamarin.
I took a quick look at some MAUI pre-releases a while ago and did not get the impression that things will be much different there.

Flutter is an amazing technology, the only downside is that it isn't possible to share code with the backend, if you need a web application and a mobile application you can't share any code.
Flutter Web did never work for us in production as it doesn't really deliver a "native" web feel.

I've put together a VERY ROUGH Flutter sample, that could be a starting point for you:
https://github.com/stefffdev/NubeSync/tree/master/samples/Clients/Flutter/nubesyncflutter

Keep in mind that this is completely untested and could not be further away from production-ready!

**Comment by stevehayles** [comment]
@stefffdev Absolutely amazing! This is the perfect kickstart and much more complete than you suggest...   I was planning out my approach to the problem and was going to use Moor (now Drift) as the persistence library as it has a few features that pulled it more into line with the C# version (expression queries, code first models etc) but I think this is fairly easily adapted and might not be necessary.

Thank you again for your assistance, I may fork my version for a while but if anything more substantial comes from it I will make everything available to you.  I will start testing now, my experience of these types of sync frameworks are that there can be some nasty and difficult to track edge cases.  Fantastic work, if there is anything I can do to help with the C# version then please don't hesitate to ask

**Comment by stefffdev** [comment]
Cool thx, wish you all the best with your project!
