### ISSUE TITLE
Viable alternative to Azure Mobile Apps?

### ISSUE THREAD

**Issue by chbjh** [stefffdev/NubeSync#37]
Hi @stefffdev,

Firstly I'd just like to say the project looks great.

I'm in the process of weighing up whether or not this is a viable replacement for Azure Mobile Apps.

On [your website](https://www.lakedice.com/nubesync-modern-net-offline-data-sync/), you mention that you're just using this in greenfield projects for now. As this article was written a couple of years ago, I'm interested to know if you think it's stood the test of time and is fit for heavy production use?

Thanks!

**Comment by stefffdev** [comment]
Hi @chbjh, thanks for reaching out!

The app mentioned on the website got cancelled before we could replace Azure Mobile Sync with NubeSync.
Therefore I'm currently using NubeSync only in some "lighter scenarios", meaning mostly internal LOB apps.

But I was in contact with some users, that use it in heavier consumer-facing production apps.

Maybe just try it out with a quick demo, and just in case you don't know, Microsoft is on the mobile data sync train again with this package: https://github.com/Azure/azure-mobile-apps

**Comment by chbjh** [comment]
Hi @stefffdev,

Appreciate the reply. I was aware of Microsoft's new efforts with Azure Mobile Apps, but I was just under the impression that it was only a rewrite for .NET Core? Nothing too special right?

If you don't mind, please could you comment on what is the heaviest use case you're aware of for this project? I'm interested to know the kind of numbers we're talking about in terms of users etc.

Many thanks.

**Comment by stefffdev** [comment]
I'm not sure what Microsoft is planning with it's efforts but it seems to be rather low-priority for them, but that's just an outside guess.

Unfortunately I can't give any details on any production use, I have not been in contact with any users lately - and even if I had numbers, you could not guarantee that these numbers apply to your use-case as well.

I'd recommend to just try it out with a realistic amount of data to sync - from my experience not the number of users is important (can be handled by scaling the infrastructure) but the amount of data each user has to sync.

**Comment by chbjh** [comment]
So the main concern I have is that the app I am thinking about using this for has some tables which have ~100 columns and some of these columns are varbinary(max) (to store image data) so some records can be ~500KB...

I guess I'd have to just try it and see how it behaves, but in principle would you expect it to handle that? Azure Mobile Apps currently handles it, but obviously the size of some of these records can make initial syncs be fairly slow.

Thanks.

**Comment by stefffdev** [comment]
My personal opinion is that storing images in table records is never a good idea - I tried it myself on some projects and it never worked out.
Even if it's only about very small images, try syncing over a slow EDGE mobile network, the user will go nuts.

I always ended up keeping images in some Blob Storage and implement a simple "file sync", by comparing the "LastChangedAt" timestamp of your local/remote files and upload/download when the other version is newer.

**Comment by chbjh** [comment]
I agree with you but my case is unique in that the images are 1:1 with the records in the table, in addition to that, the records themselves would be almost useless without the accompanying image data, therefore having a separate sync method for the image data would be adding unwanted complexity for no real gain.
