### ISSUE TITLE
Is it possible to filter the records for use in a multi-tenant environment?

### ISSUE THREAD

**Issue by MarkLFT** [stefffdev/NubeSync#40]
We are looking at using this great sync tool, but one of our design requirements is to have the back-end be multi-tenanted.  Is there a way we can easily apply filters to ensure we do not update, add, get records in the wrong tenant?

**Comment by stefffdev** [comment]
Hi Mark!

I think you could either create a seperate database for every tenant and then create a datacontext pointing to the right database for every user

or

add a field "TenantId" to all the tables and filter by the TenantId of the user when pulling records in the controller.
When the user syncs the records also have to contain the field TenantId.

Let me know if you need any further infos!

kind regards
