### ISSUE TITLE
Points Of NetTopologySuite.Geometries are not processing from TrackAddAsync

### ISSUE THREAD

**Issue by ebasattend** [stefffdev/NubeSync#41]
Hello is there a way to process  NetTopologySuite.Geometries Point to our list<NubeOperation> with TrackAddAsync?

**Comment by stefffdev** [comment]
Hi, you can only track objects that derive from "NubeTable" and only this valid types: https://github.com/stefffdev/NubeSync/blob/51aead935589a51085a1ed2be25bd79de424d2df/src/NubeSync.Core/NubeTable.cs#L11

But it should work that you JSON serialize your "Geometries" object to a string and store that string in NubeTable field.
