### ISSUE TITLE
Updates are not pushing to the server just the inserts

### ISSUE THREAD

**Issue by juanogcx** [stefffdev/NubeSync#7]
I have detected an **important** issue while modifying an existing record and pushing to the server. The steps as follows:
1) I create a record on client. 
2) Save the record
3) Push the changes

The issue seems to be related to the operations records being lost. 

```c#
private async Task _SaveModifyOperations<T>(T item, T oldItem) where T : NubeTable, new()
{
    var operations = await _changeTracker.TrackModifyAsync(oldItem, item).ConfigureAwait(false);
    if (!await _dataStore.AddOperationsAsync(operations.ToArray()).ConfigureAwait(false))
    {
        throw new StoreOperationFailedException($"Could not save modify operations for item {item.Id}");
    }

    await _RemoveObsoleteOperationsAfterModifyAsync(operations).ConfigureAwait(false);
}
```

On after this line, ALL the operations inserted at `AddOperationsAsync` simply get deleted:
```c# 
await _RemoveObsoleteOperationsAfterModifyAsync(operations).ConfigureAwait(false);
```

So, when Pushing the records, none is found on the operations table. 

I removed the line and it seems to work but not sure if the code was there for a specific reason. 

Please advise @stefffdev, thanks!

**Comment by stefffdev** [comment]
The intention of this code is to remove obsolete operations, meaning if you modify the same field twice the first modify operation is removed, as it is not relevant to the server.

This should improve sync performance, since less records have to be processed.

Do you have a small sample reproducing this issue or more details on how you changed the record after you added it?

Thanks!

**Comment by juanogcx** [comment]
Thanks for your quick reply. This is the simplified code:

```c#
_product.Name = "NewName";
await _nubeClient.SaveAsync(product);
await _nubeClient.PushChangesAsync();
```

So based on you reply, it seems that the first -and only- change is deleted, not having the opportunity to be pushed.

**Comment by stefffdev** [comment]
I could not reproduce this issue but I found an edge case, that could cause the behavior you described.
Could you update the NubeSync nuget packages to the pre-release version **1.2.1-pre1** and report back if this fixed your problem?

If that does not help, it would be very helpful if you could reproduce the problem in a small sample solution!

Thanks

**Comment by juanogcx** [comment]
Just tried with 1.2.1-pre1 and it's not working either. I will prepare a sample app. Meanwhile, these are more steps for the tests that I did. 

So, after identifying that no records were reaching the server. I shift to using the nubesync source code on my project. 

- The record was edited and then SaveAsync() was called. 
- Put a breakpoint just before the  operations were calculated, got from the changeTracker.TrackModifyAsync
- Inspected that 2 operations were on the list: 1 for the Name property and 1 for the UpdatedAt property
- Let the dataStore.AddOperationsAsync to continue
- Opened the offline.db and verified that the 2 operations were there on the operations table
- Let the RemoveObsoleteOperationsAfterModifyAsync to continue
- Opened the offline.db and noticed that the 2 operations on the operations were gone
- Called the PushChangesAsync and, as no operations records are on the db, nothing will be pushed to the server.

**Comment by juanogcx** [comment]
@stefffdev just managed to repro on the sample app. 

Just debugged the method on `private async void Entry_Unfocused(object sender, FocusEventArgs e)` on `MainPage.cs`, and the updated record does not get updated on server either.

**Comment by stefffdev** [comment]
I could reproduce it - that was a nasty one! :(
The pre-release **1.2.1-pre2** should fix that issue, I'll provide a official update soon!

Thanks again for your effort and your contribution!

**Comment by juanogcx** [comment]
That's great news. Thanks for your quick and great support!

On another topic, a newbie question about nuget+github integration. Could you please advise me how can I debug the source code but still using the nuget packages? I was checking that there's a "SourceLink" library from MS but I can't make it work, or is not enabled on your project. Thanks!

**Comment by stefffdev** [comment]
SourceLink would be the best solution for that I guess, but I haven't added it yet, I'll create a issue for integrating it! 

Other than that you would have to download the source code and use references to the projects directly instead of using the nugets.
